### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by CDM1619** [bigaidream-projects/citylearn-2020-pikapika#1]
Hello, your work is very interesting, I would like to study the citylearn environment you use, in the process of running main.py, I found that there seems to be some missing parameter configuration files, can you please fix it, thank you very much!

:~/citylearn-2020-pikapika$ FileNotFoundError: [Errno 2] No such file or directory: '../data/Climate_Zone_2/building_attributes.json'

**Comment by bigaidream** [comment]
I guess you need to download the data from the official citylearn website.
